
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR = 53;
  public static final int UMINUS = 25;
  public static final int UPLUS = 24;
  public static final int SEMI = 28;
  public static final int INT = 52;
  public static final int LESS = 39;
  public static final int MINUS = 21;
  public static final int LSQR = 35;
  public static final int TILDA = 43;
  public static final int LCURL = 33;
  public static final int AND = 19;
  public static final int RPAR = 32;
  public static final int TYPE = 50;
  public static final int OR = 18;
  public static final int BOOL = 46;
  public static final int COMMA = 30;
  public static final int CLASS = 6;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 4;
  public static final int DOT = 45;
  public static final int OF = 5;
  public static final int EOF = 0;
  public static final int GTR = 38;
  public static final int RETURN = 17;
  public static final int PRINTLINE = 13;
  public static final int TRUE = 47;
  public static final int error = 1;
  public static final int PPLUS = 26;
  public static final int PMINUS = 27;
  public static final int NULL = 9;
  public static final int IDENT = 49;
  public static final int VOID = 8;
  public static final int ASSMNT = 44;
  public static final int EQ = 37;
  public static final int RCURL = 34;
  public static final int TIMES = 22;
  public static final int COLON = 29;
  public static final int ELSE = 2;
  public static final int READ = 11;
  public static final int NOT_EQ = 42;
  public static final int RSQR = 36;
  public static final int FINAL = 14;
  public static final int WHILE = 15;
  public static final int LESS_EQ = 40;
  public static final int FLOAT = 51;
  public static final int THEN = 7;
  public static final int END = 3;
  public static final int STRING = 54;
  public static final int LPAR = 31;
  public static final int QUESTION = 16;
  public static final int FALSE = 48;
  public static final int GTR_EQ = 41;
  public static final int VAR = 10;
  public static final int PRINT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ELSE",
  "END",
  "IF",
  "OF",
  "CLASS",
  "THEN",
  "VOID",
  "NULL",
  "VAR",
  "READ",
  "PRINT",
  "PRINTLINE",
  "FINAL",
  "WHILE",
  "QUESTION",
  "RETURN",
  "OR",
  "AND",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UPLUS",
  "UMINUS",
  "PPLUS",
  "PMINUS",
  "SEMI",
  "COLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "LCURL",
  "RCURL",
  "LSQR",
  "RSQR",
  "EQ",
  "GTR",
  "LESS",
  "LESS_EQ",
  "GTR_EQ",
  "NOT_EQ",
  "TILDA",
  "ASSMNT",
  "DOT",
  "BOOL",
  "TRUE",
  "FALSE",
  "IDENT",
  "TYPE",
  "FLOAT",
  "INT",
  "CHAR",
  "STRING"
  };
}

